# Site settings
title: Adrian Roguski professional website
description: The site is meant to be a protfolio of the author. It should show his skills and passion related to JAVA technology. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrian Roguski
user_description: Automation and Robotics graduate from the AGH Cracow University of Science and Technology with three years of expierience as Design Engineer in Norway. Currently looking for.....
user_title: Engineer
email: adrroguski@gmail.com
twitter_username: lorem_ipsum
github_username:  https://github.com/adeq123
gplus_username:  A R

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
